name = "vfdashboard"
pages_build_output_dir = "./dist"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "VFDashboard"
id = "99aff008b1124c2aa28081b5c6139403"
